name: GlobalBank
main: me.samkio.globalbank.GlobalBank
description: Adds a unique item banking system to the game.
author: Samkio
website: http://dev.bukkit.org/server-mods/globalbank/
version: 0.3
depend: [Spout]
softdepend: [Vault]
commands:
  gb:
    description: GlobalBank Commands
    usage: GlobalBank Commands

